### ISSUE TITLE
USER STORY: |user/owner| log in

### ISSUE THREAD

**Issue by Zolske** [Zolske/restaurant_manager#2]
*As a*  
**user/owner**  
*I can*  
**log in and out**  
*so that*  
**I can access my data / account**
  
---
### tasks:
- [x] create & 'register' a "custom user" model
- [x] create & register "accounts" app
- [x] create a 'super user' (admin)
- [x] create accounts/models.py with class 'CustomUser' based on 'AbstractUser'
- [x] create accounts/form.py
- [x] update accounts/admin.py
- [x] User Authentication
- [x] write tests

**Comment by Zolske** [comment]
The story  has been implemented into the project.
