### ISSUE TITLE
USER STORY: |user/owner| reset password

### ISSUE THREAD

**Issue by Zolske** [Zolske/restaurant_manager#31]
*As a*  
**user/owner**  
*I can*  
**reset my password**  
*so that*  
**I can log in again**
  
---
### tasks:
- [x] add template for password_reset_complete, confirms that password has been reset (*using Crisp*)
- [x] add template for password_reset_confirm, user enters new password and confirms (*using Crisp*)
- [x] add template for password_reset_done, inform user that email has been send to inbox (*using Crisp*)
- [x] add template for password_reset_form, the form to reset the password (*using Crisp*)
- [x] add link to 'log in' page to navigate to the 'reset password' page
- [x] add SendGrid to enable password reset via email
- [x] manual test on heroku app
